# Generated by Django 4.2.11 on 2026-04-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
