# Generated by Django 4.2.11 on 2026-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('ALL', 'All Users'), ('EXECUTIVE_BOARD', 'Executive Board'), ('STAFF', 'Platform Staff'), ('PARTNER', 'Partners & Investors'), ('STUDENT', 'Students Only'), ('TEACHER', 'Teachers Only'), ('PARENT', 'Parents Only'), ('BURSAR', 'Bursar Only'), ('LIBRARIAN', 'Librarian Only'), ('SCHOOL_ALL', 'All School Members'), ('PERSONAL', 'Personal Message')], max_length=20),
        ),
    ]
