-- =============================================================================
--  EduIgnite Platform – PostgreSQL Production Setup Script
--  Run as a superuser (postgres) or as the eduignite DB owner.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 1 – DATABASE & ROLE CREATION
-- Run this block connected to the 'postgres' database as superuser.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1.1  Create application role
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'eduignite_user') THEN
    CREATE ROLE eduignite_user
      LOGIN
      PASSWORD 'EduIgnite_DB_2026!'
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE;
    RAISE NOTICE 'Role eduignite_user created.';
  ELSE
    RAISE NOTICE 'Role eduignite_user already exists – skipping.';
  END IF;
END
$$;

-- 1.2  Create database
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'eduignite') THEN
    PERFORM dblink_exec('dbname=postgres', 'CREATE DATABASE eduignite
      OWNER = eduignite_user
      ENCODING = ''UTF8''
      LC_COLLATE = ''en_US.UTF-8''
      LC_CTYPE   = ''en_US.UTF-8''
      TEMPLATE = template0');
    RAISE NOTICE 'Database eduignite created.';
  ELSE
    RAISE NOTICE 'Database eduignite already exists – skipping.';
  END IF;
END
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 2 – CONNECT TO eduignite DATABASE
-- \c eduignite   (psql command – run remaining SQL after switching)
-- ─────────────────────────────────────────────────────────────────────────────

-- 2.1  Grant privileges
GRANT ALL PRIVILEGES ON DATABASE eduignite TO eduignite_user;
GRANT ALL ON SCHEMA public TO eduignite_user;

-- 2.2  Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";        -- UUID generation
CREATE EXTENSION IF NOT EXISTS "pg_trgm";          -- trigram search (fast LIKE)
CREATE EXTENSION IF NOT EXISTS "btree_gin";        -- GIN index on composite types
CREATE EXTENSION IF NOT EXISTS "unaccent";         -- accent-insensitive search
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"; -- query performance tracking

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 3 – PERFORMANCE & CONNECTION TUNING
-- Add these lines to postgresql.conf (restart required)
-- ─────────────────────────────────────────────────────────────────────────────

/*  postgresql.conf recommendations for a 4 vCPU / 8 GB RAM production server:

    max_connections            = 100
    shared_buffers             = 2GB
    effective_cache_size       = 6GB
    maintenance_work_mem       = 512MB
    work_mem                   = 64MB
    wal_buffers                = 16MB
    min_wal_size               = 1GB
    max_wal_size               = 4GB
    checkpoint_completion_target = 0.9
    random_page_cost           = 1.1        # SSD
    effective_io_concurrency   = 200        # SSD
    default_statistics_target  = 100
    log_min_duration_statement = 1000       # log queries > 1 s
    log_connections            = on
    log_disconnections         = on
    autovacuum                 = on
    autovacuum_vacuum_scale_factor    = 0.05
    autovacuum_analyze_scale_factor   = 0.02
*/

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 4 – AFTER DJANGO MIGRATIONS (run after: python manage.py migrate)
-- ─────────────────────────────────────────────────────────────────────────────

-- 4.1  Performance indexes not generated by Django ORM

-- Fast search on user name (trigram)
CREATE INDEX IF NOT EXISTS idx_users_name_trgm
    ON users USING gin (name gin_trgm_ops);

-- Fast search on school name
CREATE INDEX IF NOT EXISTS idx_schools_name_trgm
    ON schools USING gin (name gin_trgm_ops);

-- Index for active sessions lookup (attendance)
CREATE INDEX IF NOT EXISTS idx_attendance_session_date_school
    ON attendance_attendancesession (school_id, date DESC);

-- Covering index for grade lookups by student+year
CREATE INDEX IF NOT EXISTS idx_grades_student_seq
    ON grades_grade (student_id, sequence_id, score DESC);

-- Covering index for fee payment status queries
CREATE INDEX IF NOT EXISTS idx_payment_status_school
    ON fees_payment (school_id, status, payment_date DESC);

-- Covering index for message thread queries
CREATE INDEX IF NOT EXISTS idx_message_convo_created
    ON chat_message (conversation_id, created_at DESC)
    WHERE is_deleted = FALSE;

-- Partial index for active announcements
CREATE INDEX IF NOT EXISTS idx_announcement_active
    ON announcements_announcement (school_id, target, created_at DESC)
    WHERE (expires_at IS NULL OR expires_at > NOW());

-- Index for book availability queries
CREATE INDEX IF NOT EXISTS idx_book_available
    ON library_book (school_id, available_copies)
    WHERE available_copies > 0 AND is_active = TRUE;

-- Compound index for AI request tracking
CREATE INDEX IF NOT EXISTS idx_ai_request_user_type
    ON ai_features_airequest (user_id, request_type, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 5 – RELATIONSHIP INTEGRITY TRIGGERS
-- ─────────────────────────────────────────────────────────────────────────────

-- 5.1  Auto-update school student count when a student user is created/deleted
CREATE OR REPLACE FUNCTION fn_update_school_student_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE schools SET student_count = (
      SELECT COUNT(*) FROM users WHERE school_id = NEW.school_id AND role = 'STUDENT'
    ) WHERE id = NEW.school_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE schools SET student_count = (
      SELECT COUNT(*) FROM users WHERE school_id = OLD.school_id AND role = 'STUDENT'
    ) WHERE id = OLD.school_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.school_id IS DISTINCT FROM NEW.school_id THEN
    UPDATE schools SET student_count = (
      SELECT COUNT(*) FROM users WHERE school_id = OLD.school_id AND role = 'STUDENT'
    ) WHERE id = OLD.school_id;
    UPDATE schools SET student_count = (
      SELECT COUNT(*) FROM users WHERE school_id = NEW.school_id AND role = 'STUDENT'
    ) WHERE id = NEW.school_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_student_count ON users;
CREATE TRIGGER trg_student_count
AFTER INSERT OR UPDATE OF school_id, role OR DELETE ON users
FOR EACH ROW
WHEN (
  (TG_OP = 'INSERT'  AND NEW.role = 'STUDENT') OR
  (TG_OP = 'DELETE'  AND OLD.role = 'STUDENT') OR
  (TG_OP = 'UPDATE'  AND (NEW.role = 'STUDENT' OR OLD.role = 'STUDENT'))
)
EXECUTE FUNCTION fn_update_school_student_count();

-- 5.2  Auto-update school teacher count
CREATE OR REPLACE FUNCTION fn_update_school_teacher_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE schools SET teacher_count = (
      SELECT COUNT(*) FROM users WHERE school_id = NEW.school_id AND role = 'TEACHER'
    ) WHERE id = NEW.school_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE schools SET teacher_count = (
      SELECT COUNT(*) FROM users WHERE school_id = OLD.school_id AND role = 'TEACHER'
    ) WHERE id = OLD.school_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.school_id IS DISTINCT FROM NEW.school_id THEN
    UPDATE schools SET teacher_count = (
      SELECT COUNT(*) FROM users WHERE school_id = OLD.school_id AND role = 'TEACHER'
    ) WHERE id = OLD.school_id;
    UPDATE schools SET teacher_count = (
      SELECT COUNT(*) FROM users WHERE school_id = NEW.school_id AND role = 'TEACHER'
    ) WHERE id = NEW.school_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_teacher_count ON users;
CREATE TRIGGER trg_teacher_count
AFTER INSERT OR UPDATE OF school_id, role OR DELETE ON users
FOR EACH ROW
WHEN (
  (TG_OP = 'INSERT'  AND NEW.role = 'TEACHER') OR
  (TG_OP = 'DELETE'  AND OLD.role = 'TEACHER') OR
  (TG_OP = 'UPDATE'  AND (NEW.role = 'TEACHER' OR OLD.role = 'TEACHER'))
)
EXECUTE FUNCTION fn_update_school_teacher_count();

-- 5.3  Auto-update book available_copies when a loan status changes
CREATE OR REPLACE FUNCTION fn_sync_book_available_copies()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status = 'Active' THEN
    UPDATE library_book
    SET available_copies = GREATEST(available_copies - 1, 0)
    WHERE id = NEW.book_id;

  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.status = 'Active' AND NEW.status IN ('Returned', 'Lost') THEN
      UPDATE library_book
      SET available_copies = LEAST(available_copies + 1, total_copies)
      WHERE id = NEW.book_id AND NEW.status = 'Returned';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_book_copies ON library_bookloan;
CREATE TRIGGER trg_book_copies
AFTER INSERT OR UPDATE OF status ON library_bookloan
FOR EACH ROW
EXECUTE FUNCTION fn_sync_book_available_copies();

-- 5.4  Auto-update last_message on conversation when a new message is inserted
CREATE OR REPLACE FUNCTION fn_update_conversation_last_message()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  UPDATE chat_conversation
  SET
    last_message    = LEFT(NEW.text, 100),
    last_message_at = NEW.created_at
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_convo_last_msg ON chat_message;
CREATE TRIGGER trg_convo_last_msg
AFTER INSERT ON chat_message
FOR EACH ROW
WHEN (NEW.is_deleted = FALSE AND NEW.text IS NOT NULL)
EXECUTE FUNCTION fn_update_conversation_last_message();

-- 5.5  Prevent duplicate active sequences per school/term
CREATE OR REPLACE FUNCTION fn_enforce_single_active_sequence()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.is_active = TRUE THEN
    UPDATE grades_sequence
    SET is_active = FALSE
    WHERE school_id = NEW.school_id
      AND academic_year = NEW.academic_year
      AND id != NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_single_active_sequence ON grades_sequence;
CREATE TRIGGER trg_single_active_sequence
BEFORE INSERT OR UPDATE OF is_active ON grades_sequence
FOR EACH ROW
WHEN (NEW.is_active = TRUE)
EXECUTE FUNCTION fn_enforce_single_active_sequence();

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 6 – USEFUL VIEWS FOR REPORTING
-- ─────────────────────────────────────────────────────────────────────────────

-- 6.1  Student performance overview
CREATE OR REPLACE VIEW vw_student_performance AS
SELECT
    u.id                  AS user_id,
    u.name                AS student_name,
    u.matricule,
    s.id                  AS school_id,
    s.name                AS school_name,
    st.class_level,
    st.section,
    st.admission_number,
    st.annual_average,
    st.is_on_honour_roll,
    COUNT(g.id)           AS total_grades,
    AVG(g.score)          AS current_avg,
    MAX(g.score)          AS best_score,
    MIN(g.score)          AS lowest_score
FROM users u
JOIN students_student st   ON st.user_id     = u.id
JOIN schools s             ON s.id           = u.school_id
LEFT JOIN grades_grade g   ON g.student_id   = st.id
WHERE u.role = 'STUDENT'
GROUP BY u.id, u.name, u.matricule, s.id, s.name, st.class_level,
         st.section, st.admission_number, st.annual_average, st.is_on_honour_roll;

-- 6.2  Attendance summary per student/school
CREATE OR REPLACE VIEW vw_attendance_summary AS
SELECT
    u.id          AS user_id,
    u.name        AS student_name,
    u.school_id,
    COUNT(ar.id)                                         AS total_records,
    SUM(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END) AS present_count,
    SUM(CASE WHEN ar.status = 'absent'  THEN 1 ELSE 0 END) AS absent_count,
    SUM(CASE WHEN ar.status = 'late'    THEN 1 ELSE 0 END) AS late_count,
    ROUND(
      100.0 * SUM(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END)
      / NULLIF(COUNT(ar.id), 0), 2
    )                                                    AS attendance_rate_pct
FROM users u
JOIN students_student st              ON st.user_id    = u.id
JOIN attendance_attendancerecord ar   ON ar.student_id = st.id
WHERE u.role = 'STUDENT'
GROUP BY u.id, u.name, u.school_id;

-- 6.3  Fee payment status per school
CREATE OR REPLACE VIEW vw_fee_collection AS
SELECT
    s.id          AS school_id,
    s.name        AS school_name,
    fs.name       AS fee_structure,
    fs.amount     AS fee_amount,
    fs.academic_year,
    COUNT(p.id)               AS total_payments,
    SUM(p.amount)             AS total_collected,
    SUM(CASE WHEN p.status = 'confirmed' THEN p.amount ELSE 0 END) AS confirmed_amount,
    SUM(CASE WHEN p.status = 'pending'   THEN p.amount ELSE 0 END) AS pending_amount
FROM schools s
JOIN fees_feestructure fs ON fs.school_id = s.id
LEFT JOIN fees_payment p  ON p.fee_structure_id = fs.id AND p.school_id = s.id
GROUP BY s.id, s.name, fs.name, fs.amount, fs.academic_year;

-- 6.4  Library utilisation
CREATE OR REPLACE VIEW vw_library_utilisation AS
SELECT
    s.id   AS school_id,
    s.name AS school_name,
    COUNT(DISTINCT b.id)                                          AS total_books,
    SUM(b.total_copies)                                           AS total_copies,
    SUM(b.available_copies)                                       AS available_copies,
    COUNT(DISTINCT CASE WHEN bl.status = 'Active' THEN bl.id END) AS active_loans,
    COUNT(DISTINCT CASE WHEN bl.status = 'Overdue' THEN bl.id END) AS overdue_loans
FROM schools s
LEFT JOIN library_book     b  ON b.school_id = s.id AND b.is_active = TRUE
LEFT JOIN library_bookloan bl ON bl.book_id  = b.id
GROUP BY s.id, s.name;

-- 6.5  User communication activity
CREATE OR REPLACE VIEW vw_user_communication AS
SELECT
    u.id           AS user_id,
    u.name,
    u.role,
    u.school_id,
    COUNT(DISTINCT cp.conversation_id) AS conversations_joined,
    COUNT(DISTINCT m.id)               AS messages_sent,
    COUNT(DISTINCT ar.id)              AS announcements_read
FROM users u
LEFT JOIN chat_conversationparticipant cp ON cp.user_id       = u.id
LEFT JOIN chat_message                 m  ON m.sender_id      = u.id  AND m.is_deleted = FALSE
LEFT JOIN announcements_announcementread ar ON ar.user_id     = u.id
GROUP BY u.id, u.name, u.role, u.school_id;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 7 – STORED PROCEDURES / FUNCTIONS
-- ─────────────────────────────────────────────────────────────────────────────

-- 7.1  Compute and persist term ranks for a school/year/term
CREATE OR REPLACE PROCEDURE sp_compute_term_ranks(
    p_school_id   VARCHAR,
    p_academic_year VARCHAR,
    p_term        INTEGER
)
LANGUAGE plpgsql AS $$
BEGIN
  WITH ranked AS (
    SELECT
      id,
      ROW_NUMBER() OVER (
        PARTITION BY school_id, academic_year, term
        ORDER BY average DESC
      ) AS new_rank,
      COUNT(*) OVER (
        PARTITION BY school_id, academic_year, term
      ) AS total
    FROM grades_termresult
    WHERE school_id     = p_school_id
      AND academic_year = p_academic_year
      AND term          = p_term
  )
  UPDATE grades_termresult tr
  SET rank = r.new_rank, total_students = r.total
  FROM ranked r
  WHERE tr.id = r.id;

  RAISE NOTICE 'Term ranks updated for school=% year=% term=%',
    p_school_id, p_academic_year, p_term;
END;
$$;

-- 7.2  Mark all overdue loans for a school
CREATE OR REPLACE PROCEDURE sp_mark_overdue_loans(p_school_id VARCHAR)
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE library_bookloan
  SET status = 'Overdue'
  WHERE school_id   = p_school_id
    AND status      = 'Active'
    AND due_date    < CURRENT_DATE;

  RAISE NOTICE 'Overdue loans updated for school=%', p_school_id;
END;
$$;

-- 7.3  Get full user profile with role-specific data
CREATE OR REPLACE FUNCTION fn_get_user_profile(p_user_id UUID)
RETURNS JSON LANGUAGE plpgsql AS $$
DECLARE
  v_user    RECORD;
  v_student RECORD;
  v_result  JSON;
BEGIN
  SELECT id, name, email, matricule, role, school_id, phone,
         is_active, is_license_paid, date_joined, last_login
  INTO v_user FROM users WHERE id = p_user_id;

  IF NOT FOUND THEN
    RETURN json_build_object('error', 'User not found');
  END IF;

  IF v_user.role = 'STUDENT' THEN
    SELECT student_class, class_level, section, admission_number, annual_average, is_on_honour_roll
    INTO v_student FROM students_student WHERE user_id = p_user_id;

    v_result := json_build_object(
      'id',              v_user.id,
      'name',            v_user.name,
      'email',           v_user.email,
      'matricule',       v_user.matricule,
      'role',            v_user.role,
      'school_id',       v_user.school_id,
      'class',           v_student.student_class,
      'class_level',     v_student.class_level,
      'annual_average',  v_student.annual_average,
      'honour_roll',     v_student.is_on_honour_roll
    );
  ELSE
    v_result := row_to_json(v_user);
  END IF;

  RETURN v_result;
END;
$$;

-- 7.4  Send school-wide announcement (inserts record)
CREATE OR REPLACE PROCEDURE sp_create_announcement(
    p_school_id VARCHAR,
    p_sender_id UUID,
    p_title     TEXT,
    p_content   TEXT,
    p_target    VARCHAR DEFAULT 'SCHOOL_ALL',
    p_pinned    BOOLEAN DEFAULT FALSE
)
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO announcements_announcement
    (school_id, sender_id, title, content, target, is_pinned, view_count, created_at, updated_at)
  VALUES
    (p_school_id, p_sender_id, p_title, p_content, p_target, p_pinned, 0, NOW(), NOW());

  RAISE NOTICE 'Announcement "%" created for school=%', p_title, p_school_id;
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 8 – RELATIONSHIP INTEGRITY CHECKS (run periodically)
-- ─────────────────────────────────────────────────────────────────────────────

-- 8.1  Find students with no parent link
SELECT
    u.matricule, u.name, u.school_id
FROM users u
JOIN students_student st ON st.user_id = u.id
WHERE u.role = 'STUDENT'
  AND NOT EXISTS (
      SELECT 1 FROM students_parentstudentlink l WHERE l.student_id = st.id
  );

-- 8.2  Find schools missing settings
SELECT s.id, s.name
FROM schools s
WHERE NOT EXISTS (
    SELECT 1 FROM school_settings ss WHERE ss.school_id = s.id
);

-- 8.3  Find teachers assigned to no subjects
SELECT u.matricule, u.name, u.school_id
FROM users u
WHERE u.role = 'TEACHER'
  AND NOT EXISTS (
      SELECT 1 FROM grades_subject gs WHERE gs.teacher_id = u.id AND gs.is_active = TRUE
  );

-- 8.4  Find overdue loans not yet marked (useful for manual audits)
SELECT
    bl.id,
    u.name      AS borrower,
    b.title     AS book,
    bl.due_date,
    CURRENT_DATE - bl.due_date AS days_overdue
FROM library_bookloan bl
JOIN library_book  b  ON b.id  = bl.book_id
JOIN users         u  ON u.id  = bl.borrower_id
WHERE bl.status   = 'Active'
  AND bl.due_date < CURRENT_DATE
ORDER BY days_overdue DESC;

-- 8.5  Unread announcements count per user (sample – top 20)
SELECT
    u.name, u.role, u.school_id,
    COUNT(a.id) - COUNT(ar.id) AS unread_count
FROM users u
JOIN announcements_announcement a
    ON (a.school_id = u.school_id OR a.school_id IS NULL)
    AND a.target IN ('ALL', 'SCHOOL_ALL', u.role)
    AND (a.expires_at IS NULL OR a.expires_at > NOW())
LEFT JOIN announcements_announcementread ar
    ON ar.announcement_id = a.id AND ar.user_id = u.id
WHERE u.is_active = TRUE
GROUP BY u.id, u.name, u.role, u.school_id
ORDER BY unread_count DESC
LIMIT 20;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 9 – BACKUP STRATEGY COMMANDS
-- ─────────────────────────────────────────────────────────────────────────────

/*
-- Full database backup (run from shell as postgres user):
pg_dump -U eduignite_user -d eduignite -F c -Z 9 \
  -f /backups/eduignite_$(date +%Y%m%d_%H%M%S).dump

-- Restore:
pg_restore -U eduignite_user -d eduignite --clean --if-exists \
  /backups/eduignite_20260101_020000.dump

-- Table-level backup (grades only):
pg_dump -U eduignite_user -d eduignite -t grades_grade \
  -F c -f /backups/grades_$(date +%Y%m%d).dump

-- Automated daily backup cron (add to postgres crontab):
0 2 * * * pg_dump -U eduignite_user -d eduignite -F c -Z 9 \
  -f /backups/eduignite_$(date +\%Y\%m\%d_\%H\%M\%S).dump \
  && find /backups -name "*.dump" -mtime +30 -delete
*/

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 10 – GRANT MINIMUM PRIVILEGES (production hardening)
-- ─────────────────────────────────────────────────────────────────────────────

-- After migrations, lock down to SELECT/INSERT/UPDATE/DELETE only
-- (no DROP TABLE, CREATE TABLE, ALTER TABLE from the app user)
REVOKE CREATE ON SCHEMA public FROM eduignite_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO eduignite_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO eduignite_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eduignite_user;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO eduignite_user;

-- Apply to future tables too
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO eduignite_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO eduignite_user;

-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 11 – QUICK HEALTH CHECK QUERIES
-- ─────────────────────────────────────────────────────────────────────────────

-- Count users by role
SELECT role, COUNT(*) AS total
FROM users
GROUP BY role
ORDER BY total DESC;

-- School summary
SELECT
    s.id, s.name, s.status,
    s.student_count, s.teacher_count,
    ss.academic_year, ss.term,
    ss.licence_expiry
FROM schools s
JOIN school_settings ss ON ss.school_id = s.id
ORDER BY s.name;

-- Active conversations per school
SELECT
    COALESCE(c.school_id, 'PLATFORM') AS school,
    c.conversation_type,
    COUNT(*) AS total,
    SUM((SELECT COUNT(*) FROM chat_message m WHERE m.conversation_id = c.id AND NOT m.is_deleted)) AS total_messages
FROM chat_conversation c
WHERE c.is_active = TRUE
GROUP BY c.school_id, c.conversation_type
ORDER BY total_messages DESC;

-- ─────────────────────────────────────────────────────────────────────────────
-- END OF SCRIPT
-- =============================================================================
