# Generated by Django 4.2.11 on 2026-04-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_platformsettings_logo_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
